### ISSUE TITLE
missing Frequency Xlating FIR Filter

### ISSUE THREAD

**Issue by SvenKrebs** [ghostop14/gr-clenabled#8]
Hello ghostop14,
thank you for this great project!

Will the missing channelizers, especially the Frequency Xlating FIR Filter, also added to your project?

This would make me very happy. :-)

**Comment by ghostop14** [comment]
Hi SvenKrebs, I took a look through the code and I think the best performance would be to just chain a decimator, the GPU filter, and a rotator (or use the freq shift block in gr-lfast that cuts the manual 2PI/samp_rate calc you have to add out of your flowgraph).  That's all the XLATing filter is really doing anyway (just combining them in a single block).  This would also benefit in that the rotator/freq shift blocks use volk whereas the XLATing blocks don't because they rotate/decimate in a for loop one sample at a time.  

For the parallelism on the GPU I'd need to use sin/cos for the shift rather than what a basic rotator does sequentially, which would add cycles to the GPU code, and the decimation would have to be done outside the GPU anyway.  So I think the best overall performance may be Decimate->FIR/FFT filter on the GPU->rotator/shift block (since they use volk).

I could add a hierarchical block in clenabled to do it but somehow that doesn't feel right since only one of the pieces would actually be on the GPU.

**Comment by SvenKrebs** [comment]
Thank you for the answer.

I cant find a block in gnuradio companion, that does decimation only.

Is the one your are talking about in gr-lfast ?

I wonder if gpu support could also be added to the gr-gsm receiver- and the
gr-gsm-adapter block, did you ever looked at it?

Bye.



Am Mi., 1. Jan. 2020 um 21:04 Uhr schrieb ghostop14 <
notifications@github.com>:

**Comment by ghostop14** [comment]
Hi SvenKrebs, there is a general block in gnuradio core.  The best block for general decimation would be to look at the rational resampler.  Just set the decimation to what you'd like and leave the interpolation at 1.  Putting it first before the filter reduces downstream processing throughput by the decimation so it's best to do it first if you can.  I haven't looks at the other GSM blocks.  SIMD on GPUs is highly dependent on the algorithms.  Anything you can do in parallel on a sample set (like general multiplication by a scalar at the simplest) scales well to a GPU.  Calculations that have sequential calculations like PLL loops (things where out[n] is a function of out[n-1] for instance) doesn't scale to a GPU for parallel processing.  So I'd have to look at the algorithms.

**Comment by SvenKrebs** [comment]
Thank you again for the information.
Would be great if you can look at the algorithms if you got some time.

Am Fr., 3. Jan. 2020 um 15:15 Uhr schrieb ghostop14 <
notifications@github.com>:
